package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* lunes 13 de marzo de 2023 15H51' CST
*/

public interface CalculatorOperations 
{
  float add (float x, float y);
  float subtract (float x, float y);
  float multiply (float x, float y);
  float divide (float x, float y);
} // interface CalculatorOperations
